# Generated by Django 6.0.5 on 2026-06-07 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='logincode',
            index=models.Index(fields=['user', 'code'], name='login_user_code_idx'),
        ),
    ]
