# Generated by Django 6.0.5 on 2026-06-12 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug / Identificador URL')),
                ('icon_class', models.CharField(blank=True, help_text='Clase de FontAwesome o Bootstrap Icons.', max_length=50, null=True)),
                ('color_hex', models.CharField(default='#007bff', help_text='Color en formato HEX para las etiquetas.', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ShowPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Total del Lugar')),
                ('viewbox', models.CharField(default='0 0 1000 1000', help_text='Dimensiones originales del lienzo SVG para el escalado dinámico.', max_length=50)),
            ],
            options={
                'verbose_name': 'Estadio / Recinto',
                'verbose_name_plural': '🏢 Estadios y Recintos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del Evento / Banda')),
                ('description', models.TextField(verbose_name='Descripción del Evento')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de la Imagen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shows.category')),
                ('organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador / Productora')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora de la función')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio mínimo estimado para marketing', max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.event')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.showplace')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Sector')),
                ('slug', models.SlugField(help_text='Identificador único para el ID del SVG.', max_length=100)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Máxima Física del Sector')),
                ('polygon_geometry', models.JSONField(help_text='Diccionario con el tipo de forma de SVG y sus puntos/coordenadas correspondientes.', verbose_name='Medidas del Polígono (JSON)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='shows.showplace', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayoutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(default='INFRA', max_length=20)),
                ('geometry', models.JSONField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='shows.showplace')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Calle y Número')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Provincia/Estado')),
                ('country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shows.showplace')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio para este Show')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Entradas Vendidas')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Entradas Reservadas')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sectors', to='shows.sector')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sectors', to='shows.show')),
            ],
            options={
                'unique_together': {('show', 'sector')},
            },
        ),
    ]
