# Generated by Django 6.0.5 on 2026-05-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Total del Lugar')),
                ('viewbox', models.CharField(default='0 0 1000 1000', help_text='Dimensiones originales del lienzo SVG para el escalado dinámico.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Sector')),
                ('slug', models.SlugField(help_text='Identificador único para el ID del SVG (ej: platea-alta).', max_length=100)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad del Sector')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Entradas Vendidas')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Entradas Reservadas')),
                ('available', models.PositiveIntegerField(default=0, verbose_name='Entradas Disponibles')),
                ('polygon_geometry', models.JSONField(help_text='Diccionario con el tipo de forma de SVG y sus puntos/coordenadas correspondientes.', verbose_name='Medidas del Polígono (JSON)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='shows.showplace', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Calle y Número')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Provincia/Estado')),
                ('country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shows.showplace')),
            ],
        ),
    ]
