# Generated by Django 6.0.5 on 2026-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_showplace_sector_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio del Sector'),
        ),
    ]
