# Generated by Django 6.0.5 on 2026-05-27 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_sector_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayoutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(default='INFRA', max_length=20)),
                ('geometry', models.JSONField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='shows.showplace')),
            ],
        ),
    ]
