# Generated by Django 6.0.5 on 2026-05-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_maplayoutobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='available',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='sold',
        ),
        migrations.AlterField(
            model_name='sector',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacidad Máxima Física del Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(help_text='Identificador único para el ID del SVG.', max_length=100),
        ),
        migrations.CreateModel(
            name='ShowSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio para este Show')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Entradas Vendidas')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Entradas Reservadas')),
                ('available', models.PositiveIntegerField(default=0, verbose_name='Entradas Disponibles')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sectors', to='shows.sector')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sectors', to='shows.show')),
            ],
            options={
                'unique_together': {('show', 'sector')},
            },
        ),
    ]
