# Generated by Django 6.0.5 on 2026-05-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_remove_sector_available_remove_sector_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug / Identificador URL')),
                ('icon_class', models.CharField(blank=True, help_text="Clase de FontAwesome o Bootstrap Icons (ej: 'bi-music-note-beamed').", max_length=50, null=True)),
                ('color_hex', models.CharField(default='#007bff', help_text="Color en formato HEX para las etiquetas del frontend (ej: '#ffc107').", max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='shows.category', verbose_name='Categoría'),
        ),
    ]
